import Head from 'next/head'
import Feed from '../components/feed/Feed'
import AppHeader from '../components/header/AppHeader'


export default function Home() {
  return (
    <>
      <Head>
        <title>Instagrar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gray-50 min-h-screen">

        <AppHeader />
        <Feed  />
      </div>

    </>
  )
}
