import { ClientSafeProvider, getProviders } from 'next-auth/react'
import { useState, createContext } from "react";
import Head from 'next/head'
import Feed from '../components/feed/Feed'
import AppHeader from '../components/header/AppHeader'
// import {
//   RecoilRoot,
//   atom,
//   selector,
//   useRecoilState,
//   useRecoilValue,
// } from 'recoil';
import UploadModal from '../components/UploadModal';
import { modalState } from '../atom/modalAtom';

export const providersContext = createContext<ClientSafeProvider | null>(null)



export default function Home({ providers }: { providers: ClientSafeProvider[] }) {
  // const [isOpen, setIsOpen] = useRecoilState(modalState)
  const provider = Object.values(providers)[0]
  return (
    <>
      <Head>
        <title>Instagrar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <providersContext.Provider value={provider}>

          <div className="bg-gray-50 min-h-screen" >

            <AppHeader />
            <Feed />
            <UploadModal />
          </div>

      </providersContext.Provider>

    </>
  )
}


export async function getServerSideProps() {
  const providers = await getProviders()
  return {
    props: { providers }
  }
}